### ISSUE TITLE
在入口页面中找不到这个组件

### ISSUE THREAD

**Issue by zhaole0451** [anyongjin/klinechart-ui-demo#3]
在pages目录下面的kline.vue中，第一部分，找不到  KlineChart 这个模块呢？

希望能解答这个初级问题，感谢！
< template>
  < KlineChart  :has-right="false"/>
< /template>

**Comment by anyongjin** [comment]
这个组件位于`components\kline\chart.vue`，因为项目用的nuxt框架，它会自动在每个页面中导入需要的组件，组件名称会首字母大写，所以`kline\chart`对应的是KlineChart，如果您运行报错，可以尝试手动导入这个组件：
```typescript
import Chart from "~/components/kline/chart.vue"
```
然后`<Chart ... />`

如果需要nuxt文档，可以[看这里](https://nuxt.com/docs/getting-started/introduction)

**Comment by zhaole0451** [comment]
非常感谢，祝工作愉快~
